version: 1
user: cvmfsunpacker
cvmfs_repo: 'unpacked.cern.ch'
output_format: 'https://gitlab-registry.cern.ch/unpacked/sync/$(image)'
input:
    - 'https://registry.hub.docker.com/library/centos:centos7'
    - 'https://registry.hub.docker.com/engineren/ilcsoft:test'
    - 'https://registry.hub.docker.com/uegede/weather:latest'
    - 'https://registry.hub.docker.com/ville761/af2:latest'
    - 'https://registry.hub.docker.com/dseitova/bars-image:v2'
    - 'https://registry.hub.docker.com/stimela/cubicalddf:1.4.6'
    - 'https://registry.hub.docker.com/stimela/breizorro:1.7.1'
    - 'https://registry.hub.docker.com/stimela/ddfacet:1.7.0'
    - 'https://ghcr.io/watonomous/actions-runner-image:*'
    - 'https://ghcr.io/dluitz/bonn-comp-phys-c--dev:main'
    - 'https://Simulation1:v1.0.0'
    - 'https://registry.gitlab.com/prateek5694532/test_cicd_includev2:v0.1.0'
    - 'https://registry.gitlab.com/prateek5694532/test_cicd_includev2:v0.0.1'
    - 'https://simulation:latest'
    - 'https://simulation:late1'
    - 'https://simulation:late2'
    - 'https://linc:late1'
    - 'https://linc:late2'
    - 'https://QCD:l1'
